/** Declaration file generated by dts-gen */

export = scarbon;

declare class scarbon {
  constructor(options?: options);
  png(code: string, options?: options): buffer;
  pretty(code: string, options?: options): buffer;
  svg(code: string, options?: options): string;
  static load(theme: string | object | buffer): object;
}

declare interface options {
  formatter?: formatOptions
  background?: string
  padding?: number
  width?: number
  radius?: number
  size?: number
  font?: string
  base?: string
  lang?: string
  theme?: string | object
}

declare interface formatOptions {
  format?: string
  trailingComma?: string
  tab?: number
  length?: number
  bracketSpacing?: boolean
  semicolon?: boolean
  singleQuote?: boolean
  disabled?: boolean
}