/** Declaration file generated by dts-gen */

export = scarbon;

declare class scarbon {
  constructor(options?: Options);
  png(code: string, options?: Options): Buffer;
  pretty(code: string, options?: Options): Buffer;
  svg(code: string, options?: Options): string;
  static load(theme: string | object | Buffer): object;
}

declare interface Options {
  formatter?: {
    format?: string
    trailingComma?: string
    tab?: number
    length?: number
    bracketSpacing?: boolean
    semicolon?: boolean
    singleQuote?: boolean
    disabled?: boolean
  }
  background?: string
  padding?: number
  width?: number
  radius?: number
  size?: number
  font?: string
  base?: string
  lang?: string
  theme?: string | object
}